language: python
python:
  - "3.6"
  - "nightly"

branches:
  only:
    - master

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install codecov

 #command to run tests
script: pytest --cov

after_success:
  - codecov