language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"

branches:
  only:
    - master

matrix:
  allow_failures:
    - python: "nightly"
  fast_finish: true

install:
  - pip install poetry

 #command to run tests
script: poetry run pytest --cov

after_success:
  - codecov
